const items = [
    {
        id: '01',
        image: 'images/Women_images/dress.webp',
        company: 'WAITAO',
        item_name: 'Women Summer Tunic Dress V Neck',
        original_price: 1999,
        current_price: 960,
        discount_percentage: 48,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '02',
        image: 'images/Women_images/jumpsuit1.jpg',
        company: 'LOSSKY',
        item_name: 'Summer Elegant Long Jumpsuit for Women ',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '03',
        image: 'images/Women_images/W_kurta.png',
        company: 'SEEAASH',
        item_name: 'Bagh Emerald Scalloped Kurta Set',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '04',
        image: 'images/Women_images/W_long.avif',
        company: 'ASPORA',
        item_name: 'Floral Print Anarkali Gown',
        original_price: 4330,
        current_price: 1515,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '05',
        image: 'images/Women_images/over_size.jpg',
        company: 'TOKYO TALKIES',
        item_name: 'Women Brown Printed Round Neck T-Shirt',
        original_price: 849,
        current_price: 425,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '06',
        image: 'images/Women_images/W_tshirt.webp',
        company: 'DIFFERENCE OF OPINION',
        item_name: 'Graphic Print Crew-Neck Over sized T-Shirt',
        original_price: 1299,
        current_price: 338,
        discount_percentage: 74,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '07',
        image: 'images/Women_images/W_jenes.webp',
        company: 'ROADSTER',
        item_name: 'Women Boyfriend Mid Rise Blue jenes',
        original_price: 2599,
        current_price: 650,
        discount_percentage: 74,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '08',
        image: 'images/Women_images/jenes.webp',
        company: 'DEV TRAINS',
        item_name: 'Women Ragular Need Rise Blue jenes',
        original_price: 2499,
        current_price: 750,
        discount_percentage: 70,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '09',
        image: 'images/Women_images/saree.avif',
        company: 'VARUN BAHL',
        item_name: 'Ivory Saree Georgette Printed Summer Flower For Women',
        original_price: 19500,
        current_price: 15600,
        discount_percentage: 20,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '10',
        image: 'images/Women_images/W_suit.webp',
        company: 'POWER SUTRA',
        item_name: 'Single-Breasted Two-Piece Formal Suit',
        original_price: 8371,
        current_price: 5859,
        discount_percentage: 30,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '11',
        image: 'images/Women_images/W_T.jpg',
        company: 'ZIYEBERRY',
        item_name: 'Women Fitted Crop Top With Ruffled Shrug',
        original_price: 1999,
        current_price: 750,
        discount_percentage: 62,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '12',
        image: 'images/Women_images/W_innerware.jpg',
        company: 'CUKOO',
        item_name: 'Padded Black Halter Neck Swimwear',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }

];